### ISSUE TITLE
Can't /give an item with a damage value higher than 127

### ISSUE THREAD

**Issue by Gimlao** [Bukkit/ScrapBukkit#14]
For example, /give 373:127 will work, but /give 373:128 will throw an internal error:

[GRAVE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'give' in plugin ScrapBukkit v1.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:480)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:822)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:782)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:765)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:114)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:83)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:569)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:461)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NumberFormatException: Value out of range. Value:"128" Radix:10
        at java.lang.Byte.parseByte(Unknown Source)
        at java.lang.Byte.valueOf(Unknown Source)
        at java.lang.Byte.valueOf(Unknown Source)
        at com.dinnerbone.bukkit.scrap.commands.GivePluginCommand.onCommand(GivePluginCommand.java:33)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 12 more

**Comment by Gimlao** [comment]
I was trying to give some potions.

( http://www.minecraftwiki.net/wiki/Data_values#Potions )
